"""Built-in domain terminology database for the Smart Term Locker.

Each entry maps an English source term to one of:
  - None  : keep the original English term as-is in the output.
  - str   : replace with this Vietnamese/standard translation.

Entries are matched case-insensitively against the source text, but the
*original casing* from the source sentence is preserved in the output when
the target is None (keep-original).

Sections
--------
AI / Machine Learning
Software / DevOps / Cloud
Hardware & Electronics
Mathematics & Statistics
Biology & Genetics
Medicine & Healthcare
Chemistry & Physics
Finance & Economics
General Science
Media & Content
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Convention:
#   None  → keep original English term verbatim
#   "str" → replace with this Vietnamese standard term
# ---------------------------------------------------------------------------

DOMAIN_TERMS: dict[str, str | None] = {

    # ── AI / Machine Learning ──────────────────────────────────────────────
    "LLM": None,
    "LLMs": None,
    "GPT": None,
    "GPT-4": None,
    "GPT-4o": None,
    "ChatGPT": None,
    "Claude": None,
    "Gemini": None,
    "BERT": None,
    "T5": None,
    "RAG": None,
    "RLHF": None,
    "RLAIF": None,
    "SFT": None,
    "DPO": None,
    "PPO": None,
    "LoRA": None,
    "QLoRA": None,
    "transformer": None,
    "transformers": None,
    "attention mechanism": None,
    "self-attention": None,
    "multi-head attention": None,
    "embedding": None,
    "embeddings": None,
    "vector embedding": None,
    "fine-tuning": None,
    "fine-tune": None,
    "pre-training": None,
    "pre-trained": None,
    "inference": "suy luận",
    "hallucination": "ảo giác (hallucination)",
    "hallucinations": "ảo giác (hallucinations)",
    "token": None,
    "tokens": None,
    "tokenizer": None,
    "tokenization": None,
    "prompt": None,
    "prompts": None,
    "prompt engineering": None,
    "zero-shot": None,
    "few-shot": None,
    "chain-of-thought": None,
    "context window": None,
    "context length": None,
    "temperature": None,   # keep — meaning differs from "nhiệt độ" in this context
    "top-p": None,
    "top-k": None,
    "beam search": None,
    "greedy decoding": None,
    "softmax": None,
    "sigmoid": None,
    "relu": None,
    "ReLU": None,
    "dropout": None,
    "batch normalization": None,
    "layer normalization": None,
    "backpropagation": "lan truyền ngược",
    "gradient descent": "hạ gradient",
    "stochastic gradient descent": "hạ gradient ngẫu nhiên",
    "SGD": None,
    "Adam": None,
    "AdamW": None,
    "learning rate": "tốc độ học",
    "epoch": None,
    "batch size": None,
    "overfitting": "overfitting (quá khớp)",
    "underfitting": "underfitting (thiếu khớp)",
    "regularization": "chính quy hóa",
    "cross-entropy": "cross-entropy",
    "loss function": "hàm mất mát",
    "accuracy": "độ chính xác",
    "precision": "độ chính xác",
    "recall": "độ nhạy",
    "F1 score": None,
    "AUC": None,
    "ROC": None,
    "convolutional neural network": "mạng nơ-ron tích chập",
    "CNN": None,
    "recurrent neural network": "mạng nơ-ron hồi quy",
    "RNN": None,
    "LSTM": None,
    "GAN": None,
    "VAE": None,
    "diffusion model": None,
    "stable diffusion": None,
    "Stable Diffusion": None,
    "DALL-E": None,
    "Midjourney": None,
    "multimodal": "đa phương thức",
    "vision language model": "mô hình ngôn ngữ-thị giác",
    "VLM": None,
    "object detection": "phát hiện đối tượng",
    "image segmentation": "phân đoạn ảnh",
    "natural language processing": "xử lý ngôn ngữ tự nhiên",
    "NLP": None,
    "named entity recognition": "nhận dạng thực thể có tên",
    "NER": None,
    "sentiment analysis": "phân tích cảm xúc",
    "speech recognition": "nhận dạng giọng nói",
    "ASR": None,
    "text-to-speech": "chuyển văn bản thành giọng nói",
    "TTS": None,
    "machine translation": "dịch máy",
    "NLLB": None,
    "Whisper": None,
    "latency": "độ trễ",
    "throughput": "thông lượng",
    "benchmark": None,
    "MMLU": None,
    "HumanEval": None,
    "agent": None,        # keep in AI context
    "multi-agent": None,
    "agentic": None,
    "tool use": None,
    "function calling": None,
    "retrieval augmented generation": "tạo sinh tăng cường truy xuất",
    "vector database": "cơ sở dữ liệu vector",
    "knowledge graph": "đồ thị tri thức",
    "Hugging Face": None,
    "OpenAI": None,
    "Anthropic": None,
    "DeepMind": None,
    "Google DeepMind": None,
    "Meta AI": None,
    "Mistral": None,
    "Llama": None,
    "Llama 3": None,
    "Mixtral": None,
    "Phi": None,
    "Gemma": None,
    "Qwen": None,

    # ── Software / DevOps / Cloud ──────────────────────────────────────────
    "API": None,
    "REST API": None,
    "GraphQL": None,
    "SDK": None,
    "CLI": None,
    "GUI": None,
    "backend": None,
    "frontend": None,
    "full-stack": None,
    "microservice": "microservice",
    "microservices": "microservices",
    "monolith": None,
    "Docker": None,
    "Kubernetes": None,
    "container": "container",
    "CI/CD": None,
    "DevOps": None,
    "MLOps": None,
    "repository": "kho lưu trữ",
    "git": None,
    "GitHub": None,
    "GitLab": None,
    "branch": "nhánh",
    "pull request": None,
    "merge": None,
    "deploy": "triển khai",
    "deployment": "triển khai",
    "cloud": "đám mây",
    "AWS": None,
    "GCP": None,
    "Azure": None,
    "serverless": None,
    "load balancer": "cân bằng tải",
    "cache": None,
    "Redis": None,
    "database": "cơ sở dữ liệu",
    "SQL": None,
    "NoSQL": None,
    "PostgreSQL": None,
    "MongoDB": None,
    "ORM": None,
    "framework": "framework",
    "library": "thư viện",
    "runtime": None,
    "debug": "gỡ lỗi",
    "debugging": "gỡ lỗi",
    "refactor": "tái cấu trúc",
    "refactoring": "tái cấu trúc",
    "open source": "mã nguồn mở",
    "open-source": "mã nguồn mở",
    "codebase": "mã nguồn",
    "algorithm": "thuật toán",
    "data structure": "cấu trúc dữ liệu",
    "asynchronous": "bất đồng bộ",
    "async": None,
    "concurrency": "đồng thời",
    "multithreading": "đa luồng",
    "JSON": None,
    "YAML": None,
    "XML": None,
    "HTTP": None,
    "HTTPS": None,
    "WebSocket": None,
    "OAuth": None,
    "JWT": None,
    "encryption": "mã hóa",
    "firewall": "tường lửa",
    "VPN": None,
    "proxy": None,
    "bandwidth": "băng thông",

    # ── Hardware & Electronics ─────────────────────────────────────────────
    "GPU": None,
    "CPU": None,
    "TPU": None,
    "NPU": None,
    "VRAM": None,
    "RAM": None,
    "SSD": None,
    "HDD": None,
    "CUDA": None,
    "ROCm": None,
    "NVIDIA": None,
    "AMD": None,
    "Intel": None,
    "semiconductor": "bán dẫn",
    "transistor": "bóng bán dẫn",
    "integrated circuit": "mạch tích hợp",
    "chip": "chip",
    "processor": "bộ xử lý",
    "memory bandwidth": "băng thông bộ nhớ",
    "clock speed": "tốc độ xung nhịp",
    "neural processing unit": "đơn vị xử lý nơ-ron",
    "edge computing": "điện toán biên",
    "IoT": None,

    # ── Mathematics & Statistics ───────────────────────────────────────────
    "matrix": "ma trận",
    "matrices": "các ma trận",
    "vector": "vectơ",
    "tensor": "tensor",
    "scalar": "vô hướng",
    "eigenvalue": "giá trị riêng",
    "eigenvector": "vectơ riêng",
    "Bayesian": "Bayesian",
    "probability": "xác suất",
    "distribution": "phân phối",
    "normal distribution": "phân phối chuẩn",
    "variance": "phương sai",
    "standard deviation": "độ lệch chuẩn",
    "correlation": "tương quan",
    "regression": "hồi quy",
    "linear regression": "hồi quy tuyến tính",
    "logistic regression": "hồi quy logistic",
    "hypothesis": "giả thuyết",
    "p-value": None,
    "statistical significance": "ý nghĩa thống kê",
    "confidence interval": "khoảng tin cậy",
    "Monte Carlo": None,
    "Markov chain": "chuỗi Markov",
    "optimization": "tối ưu hóa",

    # ── Biology & Genetics ─────────────────────────────────────────────────
    "DNA": None,
    "RNA": None,
    "mRNA": None,
    "protein": "protein",
    "genome": "hệ gen",
    "genomics": "hệ gen học",
    "gene": "gen",
    "chromosome": "nhiễm sắc thể",
    "mutation": "đột biến",
    "CRISPR": None,
    "gene editing": "chỉnh sửa gen",
    "stem cell": "tế bào gốc",
    "stem cells": "tế bào gốc",
    "mitochondria": "ty thể",
    "mitochondrion": "ty thể",
    "ATP": None,
    "cell": "tế bào",
    "neuron": "tế bào thần kinh",
    "neurons": "tế bào thần kinh",
    "synapse": "khớp thần kinh",
    "neurotransmitter": "chất dẫn truyền thần kinh",
    "cortex": "vỏ não",
    "prefrontal cortex": "vỏ não trước trán",
    "hippocampus": "hải mã",
    "enzyme": "enzyme",
    "antibody": "kháng thể",
    "antigen": "kháng nguyên",
    "immune system": "hệ miễn dịch",
    "microbiome": "hệ vi sinh vật",
    "epigenetics": "biểu sinh học",
    "biomarker": "dấu ấn sinh học",
    "sequencing": "giải trình tự",
    "photosynthesis": "quang hợp",
    "metabolism": "trao đổi chất",
    "evolution": "tiến hóa",
    "natural selection": "chọn lọc tự nhiên",
    "species": "loài",
    "organism": "sinh vật",

    # ── Medicine & Healthcare ──────────────────────────────────────────────
    "MRI": None,
    "CT scan": None,
    "PET scan": None,
    "X-ray": None,
    "biopsy": "sinh thiết",
    "diagnosis": "chẩn đoán",
    "prognosis": "tiên lượng",
    "symptom": "triệu chứng",
    "syndrome": "hội chứng",
    "pathogen": "mầm bệnh",
    "virus": "virus",
    "bacteria": "vi khuẩn",
    "vaccine": "vắc-xin",
    "clinical trial": "thử nghiệm lâm sàng",
    "placebo": "giả dược",
    "double-blind": "mù đôi",
    "randomized controlled trial": "thử nghiệm ngẫu nhiên có đối chứng",
    "RCT": None,
    "FDA": None,
    "EMA": None,
    "WHO": None,
    "pandemic": "đại dịch",
    "epidemic": "dịch bệnh",
    "oncology": "ung thư học",
    "cancer": "ung thư",
    "tumor": "khối u",
    "chemotherapy": "hóa trị",
    "immunotherapy": "liệu pháp miễn dịch",
    "antibiotic": "kháng sinh",
    "pharmacology": "dược lý học",
    "metabolism": "trao đổi chất",
    "cardiovascular": "tim mạch",
    "neurology": "thần kinh học",
    "psychiatry": "tâm thần học",
    "cognitive": "nhận thức",
    "dementia": "sa sút trí tuệ",
    "Alzheimer": "Alzheimer",
    "Parkinson": "Parkinson",
    "diabetes": "tiểu đường",
    "hypertension": "tăng huyết áp",

    # ── Chemistry & Physics ────────────────────────────────────────────────
    "quantum": "lượng tử",
    "quantum computing": "điện toán lượng tử",
    "qubit": "qubit",
    "atom": "nguyên tử",
    "molecule": "phân tử",
    "electron": "electron",
    "proton": "proton",
    "neutron": "neutron",
    "photon": "photon",
    "semiconductor": "bán dẫn",
    "superconductor": "siêu dẫn",
    "fusion": "nhiệt hạch",
    "fission": "phân hạch",

    # ── Finance & Economics ────────────────────────────────────────────────
    "ROI": None,
    "ETF": None,
    "IPO": None,
    "hedge fund": "quỹ phòng hộ",
    "venture capital": "vốn đầu tư mạo hiểm",
    "VC": None,
    "startup": "startup",
    "valuation": "định giá",
    "revenue": "doanh thu",
    "profit margin": "biên lợi nhuận",
    "liquidity": "thanh khoản",
    "derivatives": "công cụ phái sinh",
    "cryptocurrency": "tiền mã hóa",
    "blockchain": "blockchain",
    "DeFi": None,
    "NFT": None,
    "market cap": "vốn hóa thị trường",
    "inflation": "lạm phát",
    "deflation": "giảm phát",
    "GDP": None,
    "interest rate": "lãi suất",

    # ── General Science ────────────────────────────────────────────────────
    "hypothesis": "giả thuyết",
    "peer review": "bình duyệt đồng nghiệp",
    "peer-reviewed": "được bình duyệt",
    "meta-analysis": "phân tích tổng hợp",
    "systematic review": "tổng quan hệ thống",
    "replication": "tái lập",
    "control group": "nhóm đối chứng",
    "sample size": "cỡ mẫu",
    "dataset": "tập dữ liệu",
    "data augmentation": "tăng cường dữ liệu",
    "preprocessing": "tiền xử lý",
    "pipeline": "quy trình",
    "open access": "truy cập mở",
    "preprint": "bản thảo",

    # ── Media & Content ────────────────────────────────────────────────────
    "podcast": "podcast",
    "livestream": "phát sóng trực tiếp",
    "content creator": "nhà sáng tạo nội dung",
    "influencer": "influencer",
    "thumbnail": "hình thu nhỏ",
    "algorithm": "thuật toán",
    "engagement": "tương tác",
    "viral": "lan truyền",
    "trending": "xu hướng",
    "subscribe": "đăng ký",
    "subscriber": "người đăng ký",
}
